# Generated by Django 4.1.4 on 2022-12-16 21:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=50, verbose_name='Servicio')),
                ('descripcion', ckeditor.fields.RichTextField(verbose_name='Descripcion')),
                ('imagen', models.ImageField(upload_to='media', verbose_name='Imagen')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
