# Generated by Django 4.1.3 on 2022-12-17 02:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', ckeditor.fields.RichTextField(verbose_name='Descripcion')),
                ('visible', models.BooleanField(verbose_name='Visible')),
            ],
            options={
                'verbose_name': 'Categorias',
            },
        ),
        migrations.AlterModelOptions(
            name='servicios',
            options={'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.AlterField(
            model_name='servicios',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddField(
            model_name='servicios',
            name='categoria',
            field=models.ManyToManyField(blank=True, to='servicios.categoria', verbose_name='Categorias'),
        ),
    ]
