# Generated by Django 4.1.3 on 2022-12-17 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_categoria_alter_servicios_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(default='null', upload_to='media', verbose_name='Imagen'),
        ),
    ]
