# Generated by Django 4.1.3 on 2022-12-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_alter_categoria_options_categoria_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='orden',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
    ]
